name: Build flutter release
"on":
  push:
    branches:
      - desktop
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build linux
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.8.1"
          channel: "stable"
      - run: flutter config --enable-macos-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build macos
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.8.1"
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build windows
